"""create authentication tables

Revision ID: d31a87b30854
Revises: 
Create Date: 2026-08-23 17:30:19.946379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31a87b30854'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_credentials_user_id'), 'auth_credentials', ['user_id'], unique=True)
    op.create_table('auth_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('context_type', sa.String(length=30), server_default='PERSONAL', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_events_context_type'), 'auth_events', ['context_type'], unique=False)
    op.create_index(op.f('ix_auth_events_event_type'), 'auth_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_events_membership_id'), 'auth_events', ['membership_id'], unique=False)
    op.create_index(op.f('ix_auth_events_organization_id'), 'auth_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auth_events_user_id'), 'auth_events', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('context_type', sa.String(length=30), server_default='PERSONAL', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('successful', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_context_type'), 'login_attempts', ['context_type'], unique=False)
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_index(op.f('ix_login_attempts_membership_id'), 'login_attempts', ['membership_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_organization_id'), 'login_attempts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_ip', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_expires_at'), 'password_resets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_resets_is_used'), 'password_resets', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=30), server_default='PERSONAL', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_context_type'), 'refresh_tokens', ['context_type'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_membership_id'), 'refresh_tokens', ['membership_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_organization_id'), 'refresh_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('context_type', sa.String(length=30), server_default='PERSONAL', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='info', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_context_type'), 'security_events', ['context_type'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_membership_id'), 'security_events', ['membership_id'], unique=False)
    op.create_index(op.f('ix_security_events_organization_id'), 'security_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_organization_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_membership_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_context_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_organization_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_membership_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_context_type'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_is_used'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_expires_at'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_organization_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_membership_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_context_type'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_auth_events_user_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_organization_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_membership_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_event_type'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_context_type'), table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_index(op.f('ix_auth_credentials_user_id'), table_name='auth_credentials')
    op.drop_table('auth_credentials')
    # ### end Alembic commands ###
